export interface FormDestination {
  value: string;
  label: string;
}

export const FORM_DESTINATIONS = {
  es: [
    { value: "francia", label: "Francia" },
    { value: "italia", label: "Italia" },
    { value: "espana", label: "España" },
    { value: "alemania", label: "Alemania" },
    { value: "portugal", label: "Portugal" },
    { value: "grecia", label: "Grecia" },
    { value: "paises-bajos", label: "Países Bajos" },
    { value: "suiza", label: "Suiza" },
    { value: "croacia", label: "Croacia" },
    { value: "reino-unido", label: "Reino Unido" },
    { value: "albania", label: "Albania" },
    { value: "austria", label: "Austria" },
    { value: "belgica", label: "Bélgica" },
    { value: "republica-checa", label: "República Checa" },
    { value: "dinamarca", label: "Dinamarca" },
    { value: "finlandia", label: "Finlandia" },
    { value: "hungria", label: "Hungría" },
    { value: "islandia", label: "Islandia" },
    { value: "irlanda", label: "Irlanda" },
    { value: "noruega", label: "Noruega" },
    { value: "polonia", label: "Polonia" },
    { value: "rumania", label: "Rumanía" },
    { value: "suecia", label: "Suecia" },
    { value: "estados-balticos", label: "Estados Bálticos" },
    { value: "chipre", label: "Chipre" },
    { value: "escocia", label: "Escocia" },
    { value: "turquia", label: "Turquía" },
    { value: "paris", label: "París, Francia" },
    { value: "roma", label: "Roma, Italia" },
    { value: "barcelona", label: "Barcelona, España" },
    { value: "madrid", label: "Madrid, España" },
    { value: "londres", label: "Londres, Reino Unido" },
    { value: "amsterdam", label: "Ámsterdam, Países Bajos" },
    { value: "berlin", label: "Berlín, Alemania" },
    { value: "praga", label: "Praga, República Checa" },
    { value: "viena", label: "Viena, Austria" },
    { value: "estambul", label: "Estambul, Turquía" },
    { value: "atenas", label: "Atenas, Grecia" },
    { value: "lisboa", label: "Lisboa, Portugal" },
    { value: "venecia", label: "Venecia, Italia" },
    { value: "florencia", label: "Florencia, Italia" },
    { value: "milan", label: "Milán, Italia" },
    { value: "napoles", label: "Nápoles, Italia" },
    { value: "sevilla", label: "Sevilla, España" },
    { value: "valencia", label: "Valencia, España" },
    { value: "munich", label: "Múnich, Alemania" },
    { value: "budapest", label: "Budapest, Hungría" },
    { value: "dublin", label: "Dublín, Irlanda" },
    { value: "bruselas", label: "Bruselas, Bélgica" },
    { value: "ginebra", label: "Ginebra, Suiza" },
    { value: "zurich", label: "Zúrich, Suiza" },
    { value: "copenhague", label: "Copenhague, Dinamarca" },
    { value: "oslo", label: "Oslo, Noruega" },
    { value: "estocolmo", label: "Estocolmo, Suecia" },
    { value: "helsinki", label: "Helsinki, Finlandia" },
    { value: "reikiavik", label: "Reikiavik, Islandia" },
    { value: "varsovia", label: "Varsovia, Polonia" },
    { value: "cracovia", label: "Cracovia, Polonia" },
    { value: "dubrovnik", label: "Dubrovnik, Croacia" },
    { value: "split", label: "Split, Croacia" },
    { value: "santorini", label: "Santorini, Grecia" },
    { value: "mikonos", label: "Mikonos, Grecia" },
    { value: "oporto", label: "Oporto, Portugal" },
    { value: "edimburgo", label: "Edimburgo, Escocia" },
    { value: "capadocia", label: "Capadocia, Turquía" },
    { value: "otro", label: "Otro destino" },
  ],
  en: [
    { value: "francia", label: "France" },
    { value: "italia", label: "Italy" },
    { value: "espana", label: "Spain" },
    { value: "alemania", label: "Germany" },
    { value: "portugal", label: "Portugal" },
    { value: "grecia", label: "Greece" },
    { value: "paises-bajos", label: "Netherlands" },
    { value: "suiza", label: "Switzerland" },
    { value: "croacia", label: "Croatia" },
    { value: "reino-unido", label: "United Kingdom" },
    { value: "albania", label: "Albania" },
    { value: "austria", label: "Austria" },
    { value: "belgica", label: "Belgium" },
    { value: "republica-checa", label: "Czech Republic" },
    { value: "dinamarca", label: "Denmark" },
    { value: "finlandia", label: "Finland" },
    { value: "hungria", label: "Hungary" },
    { value: "islandia", label: "Iceland" },
    { value: "irlanda", label: "Ireland" },
    { value: "noruega", label: "Norway" },
    { value: "polonia", label: "Poland" },
    { value: "rumania", label: "Romania" },
    { value: "suecia", label: "Sweden" },
    { value: "estados-balticos", label: "Baltic States" },
    { value: "chipre", label: "Cyprus" },
    { value: "escocia", label: "Scotland" },
    { value: "turquia", label: "Turkey" },
    { value: "paris", label: "Paris, France" },
    { value: "roma", label: "Rome, Italy" },
    { value: "barcelona", label: "Barcelona, Spain" },
    { value: "madrid", label: "Madrid, Spain" },
    { value: "londres", label: "London, United Kingdom" },
    { value: "amsterdam", label: "Amsterdam, Netherlands" },
    { value: "berlin", label: "Berlin, Germany" },
    { value: "praga", label: "Prague, Czech Republic" },
    { value: "viena", label: "Vienna, Austria" },
    { value: "estambul", label: "Istanbul, Turkey" },
    { value: "atenas", label: "Athens, Greece" },
    { value: "lisboa", label: "Lisbon, Portugal" },
    { value: "venecia", label: "Venice, Italy" },
    { value: "florencia", label: "Florence, Italy" },
    { value: "milan", label: "Milan, Italy" },
    { value: "napoles", label: "Naples, Italy" },
    { value: "sevilla", label: "Seville, Spain" },
    { value: "valencia", label: "Valencia, Spain" },
    { value: "munich", label: "Munich, Germany" },
    { value: "budapest", label: "Budapest, Hungary" },
    { value: "dublin", label: "Dublin, Ireland" },
    { value: "bruselas", label: "Brussels, Belgium" },
    { value: "ginebra", label: "Geneva, Switzerland" },
    { value: "zurich", label: "Zurich, Switzerland" },
    { value: "copenhague", label: "Copenhagen, Denmark" },
    { value: "oslo", label: "Oslo, Norway" },
    { value: "estocolmo", label: "Stockholm, Sweden" },
    { value: "helsinki", label: "Helsinki, Finland" },
    { value: "reikiavik", label: "Reykjavik, Iceland" },
    { value: "varsovia", label: "Warsaw, Poland" },
    { value: "cracovia", label: "Krakow, Poland" },
    { value: "dubrovnik", label: "Dubrovnik, Croatia" },
    { value: "split", label: "Split, Croatia" },
    { value: "santorini", label: "Santorini, Greece" },
    { value: "mikonos", label: "Mykonos, Greece" },
    { value: "oporto", label: "Porto, Portugal" },
    { value: "edimburgo", label: "Edinburgh, Scotland" },
    { value: "capadocia", label: "Cappadocia, Turkey" },
    { value: "otro", label: "Other destination" },
  ],
  pt: [
    { value: "francia", label: "França" },
    { value: "italia", label: "Itália" },
    { value: "espana", label: "Espanha" },
    { value: "alemania", label: "Alemanha" },
    { value: "portugal", label: "Portugal" },
    { value: "grecia", label: "Grécia" },
    { value: "paises-bajos", label: "Países Baixos" },
    { value: "suiza", label: "Suíça" },
    { value: "croacia", label: "Croácia" },
    { value: "reino-unido", label: "Reino Unido" },
    { value: "albania", label: "Albânia" },
    { value: "austria", label: "Áustria" },
    { value: "belgica", label: "Bélgica" },
    { value: "republica-checa", label: "República Tcheca" },
    { value: "dinamarca", label: "Dinamarca" },
    { value: "finlandia", label: "Finlândia" },
    { value: "hungria", label: "Hungria" },
    { value: "islandia", label: "Islândia" },
    { value: "irlanda", label: "Irlanda" },
    { value: "noruega", label: "Noruega" },
    { value: "polonia", label: "Polônia" },
    { value: "rumania", label: "Romênia" },
    { value: "suecia", label: "Suécia" },
    { value: "estados-balticos", label: "Estados Bálticos" },
    { value: "chipre", label: "Chipre" },
    { value: "escocia", label: "Escócia" },
    { value: "turquia", label: "Turquia" },
    { value: "paris", label: "Paris, França" },
    { value: "roma", label: "Roma, Itália" },
    { value: "barcelona", label: "Barcelona, Espanha" },
    { value: "madrid", label: "Madrid, Espanha" },
    { value: "londres", label: "Londres, Reino Unido" },
    { value: "amsterdam", label: "Amsterdã, Países Baixos" },
    { value: "berlin", label: "Berlim, Alemanha" },
    { value: "praga", label: "Praga, República Tcheca" },
    { value: "viena", label: "Viena, Áustria" },
    { value: "estambul", label: "Istambul, Turquia" },
    { value: "atenas", label: "Atenas, Grécia" },
    { value: "lisboa", label: "Lisboa, Portugal" },
    { value: "venecia", label: "Veneza, Itália" },
    { value: "florencia", label: "Florença, Itália" },
    { value: "milan", label: "Milão, Itália" },
    { value: "napoles", label: "Nápoles, Itália" },
    { value: "sevilla", label: "Sevilha, Espanha" },
    { value: "valencia", label: "Valência, Espanha" },
    { value: "munich", label: "Munique, Alemanha" },
    { value: "budapest", label: "Budapeste, Hungria" },
    { value: "dublin", label: "Dublin, Irlanda" },
    { value: "bruselas", label: "Bruxelas, Bélgica" },
    { value: "ginebra", label: "Genebra, Suíça" },
    { value: "zurich", label: "Zurique, Suíça" },
    { value: "copenhague", label: "Copenhague, Dinamarca" },
    { value: "oslo", label: "Oslo, Noruega" },
    { value: "estocolmo", label: "Estocolmo, Suécia" },
    { value: "helsinki", label: "Helsinki, Finlândia" },
    { value: "reikiavik", label: "Reykjavik, Islândia" },
    { value: "varsovia", label: "Varsóvia, Polônia" },
    { value: "cracovia", label: "Cracóvia, Polônia" },
    { value: "dubrovnik", label: "Dubrovnik, Croácia" },
    { value: "split", label: "Split, Croácia" },
    { value: "santorini", label: "Santorini, Grécia" },
    { value: "mikonos", label: "Mykonos, Grécia" },
    { value: "oporto", label: "Porto, Portugal" },
    { value: "edimburgo", label: "Edimburgo, Escócia" },
    { value: "capadocia", label: "Capadócia, Turquia" },
    { value: "otro", label: "Outro destino" },
  ],
};
