export interface SimpleBlogPost {
  id: string;
  image: string;
  title: { es: string; en: string };
  excerpt: { es: string; en: string };
  category: string;
  categoryLabel: { es: string; en: string };
  date: string;
  readTime: number;
  featured?: boolean;
  keywords: string[];
}

export const BLOG_POSTS_SIMPLE: SimpleBlogPost[] = [
  {
    id: "circuito-balcanes",
    image: "/assets/generated_images/circuito-balcanes.png",
    title: { es: "Circuito Balcanes: Descubre 10 Naciones en un Solo Viaje", en: "Balkans Circuit: Discover 10 Nations in One Trip" },
    excerpt: { es: "Bulgaria, Grecia, Macedonia, Albania, Montenegro, Croacia, Bosnia y Serbia. La ruta mas completa por los Balcanes europeos.", en: "Bulgaria, Greece, Macedonia, Albania, Montenegro, Croatia, Bosnia and Serbia. The most complete route through the European Balkans." },
    category: "destinos",
    categoryLabel: { es: "Destinos", en: "Destinations" },
    date: "29 Dic 2024",
    readTime: 14,
    featured: true,
    keywords: ["balcanes europa", "circuito balcanes", "croacia montenegro albania"],
  },
  {
    id: "colores-de-europa",
    image: "https://images.unsplash.com/photo-1499856871958-5b9627545d1a?q=80&w=1200&auto=format&fit=crop",
    title: { es: "Colores de Europa: Tour por Francia, España e Italia", en: "Colors of Europe: Tour through France, Spain and Italy" },
    excerpt: { es: "Paris, Barcelona, Roma y mas. El circuito clasico que combina lo mejor de tres paises iconicos.", en: "Paris, Barcelona, Rome and more. The classic circuit combining the best of three iconic countries." },
    category: "destinos",
    categoryLabel: { es: "Destinos", en: "Destinations" },
    date: "29 Dic 2024",
    readTime: 12,
    featured: true,
    keywords: ["tour europa clasico", "francia espana italia", "circuito europa"],
  },
  {
    id: "encanto-mediterraneo",
    image: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=1200&auto=format&fit=crop",
    title: { es: "Encanto Mediterraneo: Italia, Francia y España Costera", en: "Mediterranean Charm: Coastal Italy, France and Spain" },
    excerpt: { es: "Costa Amalfitana, Riviera Francesa, Costa Brava. Las costas mas hermosas del Mediterraneo en un viaje.", en: "Amalfi Coast, French Riviera, Costa Brava. The most beautiful Mediterranean coasts in one trip." },
    category: "destinos",
    categoryLabel: { es: "Destinos", en: "Destinations" },
    date: "28 Dic 2024",
    readTime: 11,
    featured: true,
    keywords: ["mediterraneo europa", "costa amalfitana", "riviera francesa"],
  },
  {
    id: "ciudades-imperiales",
    image: "https://images.unsplash.com/photo-1519677100203-a0e668c92439?q=80&w=1200&auto=format&fit=crop",
    title: { es: "Ciudades Imperiales: Viena, Praga, Budapest y Estambul", en: "Imperial Cities: Vienna, Prague, Budapest and Istanbul" },
    excerpt: { es: "El legado de los grandes imperios europeos. Palacios, catedrales, puentes y cultura en un circuito inolvidable.", en: "The legacy of great European empires. Palaces, cathedrals, bridges and culture in an unforgettable circuit." },
    category: "destinos",
    categoryLabel: { es: "Destinos", en: "Destinations" },
    date: "28 Dic 2024",
    readTime: 13,
    featured: false,
    keywords: ["ciudades imperiales", "praga budapest viena", "europa central"],
  },
  {
    id: "turquia-capadocia",
    image: "https://images.unsplash.com/photo-1641128324972-af3212f0f6bd?q=80&w=1200&auto=format&fit=crop",
    title: { es: "Turquia Magica: Estambul, Capadocia y la Ruta Otomana", en: "Magical Turkey: Istanbul, Cappadocia and the Ottoman Route" },
    excerpt: { es: "Globos aerostaticos, mezquitas, bazares y paisajes lunares. Turquia es el puente entre Europa y Asia.", en: "Hot air balloons, mosques, bazaars and lunar landscapes. Turkey is the bridge between Europe and Asia." },
    category: "destinos",
    categoryLabel: { es: "Destinos", en: "Destinations" },
    date: "27 Dic 2024",
    readTime: 10,
    featured: false,
    keywords: ["turquia viaje", "capadocia globos", "estambul turismo"],
  },
  {
    id: "italia-vespa",
    image: "https://images.unsplash.com/photo-1568605114967-8130f3a36994?q=80&w=1200&auto=format&fit=crop",
    title: { es: "Italia en Vespa: Recorre la Toscana Como un Local", en: "Italy by Vespa: Explore Tuscany Like a Local" },
    excerpt: { es: "Florencia, Siena, Chianti y pueblos medievales. La forma mas autentica de vivir la Toscana italiana.", en: "Florence, Siena, Chianti and medieval towns. The most authentic way to experience Italian Tuscany." },
    category: "lujo",
    categoryLabel: { es: "Lujo", en: "Luxury" },
    date: "27 Dic 2024",
    readTime: 9,
    featured: false,
    keywords: ["italia vespa", "toscana tour", "florencia siena"],
  },
  {
    id: "mercados-navidenos",
    image: "https://images.unsplash.com/photo-1545048702-79362596cdc9?q=80&w=1200&auto=format&fit=crop",
    title: { es: "Mercados Navidenos en Europa: Viena, Praga, Estrasburgo", en: "Christmas Markets in Europe: Vienna, Prague, Strasbourg" },
    excerpt: { es: "Vin chaud, artesanias, luces y magia invernal. Los mejores mercados navidenos europeos para visitar.", en: "Mulled wine, crafts, lights and winter magic. The best European Christmas markets to visit." },
    category: "destinos",
    categoryLabel: { es: "Destinos", en: "Destinations" },
    date: "26 Dic 2024",
    readTime: 8,
    featured: false,
    keywords: ["mercados navidenos europa", "navidad viena praga", "invierno europa"],
  },
  {
    id: "ruta-del-amor",
    image: "https://images.unsplash.com/photo-1502602898657-3e91760cbb34?q=80&w=1200&auto=format&fit=crop",
    title: { es: "Ruta del Amor: Paris y Madrid para Parejas", en: "Route of Love: Paris and Madrid for Couples" },
    excerpt: { es: "La ciudad del amor y la capital espanola. Dos destinos romanticos perfectos para una escapada en pareja.", en: "The city of love and the Spanish capital. Two perfect romantic destinations for a couple's getaway." },
    category: "lujo",
    categoryLabel: { es: "Lujo", en: "Luxury" },
    date: "26 Dic 2024",
    readTime: 7,
    featured: false,
    keywords: ["paris madrid pareja", "viaje romantico europa", "luna de miel"],
  },
  {
    id: "visa-schengen-colombia-2025",
    image: "https://images.unsplash.com/photo-1569254184391-fefaab4c4c22?q=80&w=1200&auto=format&fit=crop",
    title: { es: "Guia Completa: Visa Schengen para Colombianos 2025", en: "Complete Guide: Schengen Visa for Colombians 2025" },
    excerpt: { es: "Requisitos actualizados, documentos necesarios, costo, tiempo de tramite y consejos para aprobar tu visa Schengen desde Colombia.", en: "Updated requirements, necessary documents, cost, processing time and tips to get your Schengen visa from Colombia approved." },
    category: "planificacion",
    categoryLabel: { es: "Planificacion", en: "Planning" },
    date: "25 Dic 2024",
    readTime: 12,
    featured: false,
    keywords: ["visa schengen colombia", "requisitos visa europa", "visa schengen 2025"],
  },
  {
    id: "paris-5-dias-guia",
    image: "https://images.unsplash.com/photo-1499856871958-5b9627545d1a?q=80&w=1200&auto=format&fit=crop",
    title: { es: "Paris en 5 Dias: Itinerario Perfecto para Colombianos", en: "Paris in 5 Days: Perfect Itinerary for Colombians" },
    excerpt: { es: "Torre Eiffel, Louvre, Versalles, Montmartre y mas. El itinerario dia a dia para aprovechar Paris al maximo.", en: "Eiffel Tower, Louvre, Versailles, Montmartre and more. The day by day itinerary to make the most of Paris." },
    category: "destinos",
    categoryLabel: { es: "Destinos", en: "Destinations" },
    date: "26 Dic 2024",
    readTime: 10,
    featured: true,
    keywords: ["paris 5 dias", "itinerario paris", "que hacer en paris"],
  },
  {
    id: "presupuesto-viaje-europa-2026",
    image: "https://images.unsplash.com/photo-1554224155-6726b3ff858f?q=80&w=1200&auto=format&fit=crop",
    title: { es: "Cuanto Cuesta Viajar a Europa en 2026? Presupuesto Real", en: "How Much Does It Cost to Travel to Europe in 2026? Real Budget" },
    excerpt: { es: "Desglose completo: vuelos, hoteles, comida, transporte y actividades. Presupuesto para 7, 14 y 21 dias.", en: "Complete breakdown: flights, hotels, food, transport and activities. Budget for 7, 14 and 21 days." },
    category: "dinero",
    categoryLabel: { es: "Dinero", en: "Money" },
    date: "03 Ene 2026",
    readTime: 15,
    featured: true,
    keywords: ["presupuesto europa 2026", "cuanto cuesta europa", "viaje europa precio"],
  },
  {
    id: "hoteles-lujo-paris",
    image: "https://images.unsplash.com/photo-1551882547-ff40c63fe5fa?q=80&w=1200&auto=format&fit=crop",
    title: { es: "10 Hoteles de Lujo Imperdibles en Paris 2025", en: "10 Must-Stay Luxury Hotels in Paris 2025" },
    excerpt: { es: "Ritz, Four Seasons, Le Bristol y mas. Los hoteles mas exclusivos de Paris con vista a la Torre Eiffel.", en: "Ritz, Four Seasons, Le Bristol and more. The most exclusive Paris hotels with Eiffel Tower views." },
    category: "lujo",
    categoryLabel: { es: "Lujo", en: "Luxury" },
    date: "22 Dic 2024",
    readTime: 8,
    featured: false,
    keywords: ["hoteles lujo paris", "mejores hoteles paris", "donde alojarse paris"],
  },
  {
    id: "madrid-vs-barcelona",
    image: "https://images.unsplash.com/photo-1539037116277-4db20889f2d4?q=80&w=1200&auto=format&fit=crop",
    title: { es: "Madrid vs Barcelona: Cual Elegir para tu Primer Viaje?", en: "Madrid vs Barcelona: Which One to Choose for Your First Trip?" },
    excerpt: { es: "Comparativa completa: clima, costo, atracciones, gastronomia y ambiente. Te ayudamos a decidir.", en: "Complete comparison: weather, cost, attractions, gastronomy and atmosphere. We help you decide." },
    category: "destinos",
    categoryLabel: { es: "Destinos", en: "Destinations" },
    date: "20 Dic 2024",
    readTime: 9,
    featured: false,
    keywords: ["madrid o barcelona", "espana primer viaje", "madrid barcelona diferencias"],
  },
  {
    id: "seguro-viaje-europa",
    image: "https://images.unsplash.com/photo-1450101499163-c8848c66ca85?q=80&w=1200&auto=format&fit=crop",
    title: { es: "Seguro de Viaje para Europa: Cual Elegir y Por Que es Obligatorio", en: "Travel Insurance for Europe: Which to Choose and Why It's Mandatory" },
    excerpt: { es: "Requisitos Schengen, coberturas necesarias, mejores companias y como reclamar si lo necesitas.", en: "Schengen requirements, necessary coverage, best companies and how to claim if you need it." },
    category: "planificacion",
    categoryLabel: { es: "Planificacion", en: "Planning" },
    date: "18 Dic 2024",
    readTime: 7,
    featured: false,
    keywords: ["seguro viaje europa", "seguro schengen", "seguro viaje obligatorio"],
  },
  {
    id: "roma-3-dias",
    image: "https://images.unsplash.com/photo-1552832230-c0197dd311b5?q=80&w=1200&auto=format&fit=crop",
    title: { es: "Roma en 3 Dias: Coliseo, Vaticano y Trastevere", en: "Rome in 3 Days: Colosseum, Vatican and Trastevere" },
    excerpt: { es: "Itinerario optimizado para ver lo mejor de Roma. Evita filas, mejores horarios y tips locales.", en: "Optimized itinerary to see the best of Rome. Skip lines, best times and local tips." },
    category: "destinos",
    categoryLabel: { es: "Destinos", en: "Destinations" },
    date: "16 Dic 2024",
    readTime: 8,
    featured: false,
    keywords: ["roma 3 dias", "que hacer en roma", "itinerario roma"],
  },
  {
    id: "vuelos-baratos-europa",
    image: "https://images.unsplash.com/photo-1436491865332-7a61a109cc05?q=80&w=1200&auto=format&fit=crop",
    title: { es: "Como Conseguir Vuelos Baratos a Europa desde Colombia", en: "How to Get Cheap Flights to Europe from Colombia" },
    excerpt: { es: "Mejores epocas, aerolineas, buscadores y trucos para ahorrar hasta 40% en tus vuelos.", en: "Best times, airlines, search engines and tricks to save up to 40% on your flights." },
    category: "dinero",
    categoryLabel: { es: "Dinero", en: "Money" },
    date: "14 Dic 2024",
    readTime: 10,
    featured: false,
    keywords: ["vuelos baratos europa", "pasajes europa", "vuelos colombia europa"],
  },
  {
    id: "restaurantes-michelin-paris",
    image: "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?q=80&w=1200&auto=format&fit=crop",
    title: { es: "Restaurantes Michelin en Paris: Guia para Latinoamericanos", en: "Michelin Restaurants in Paris: Guide for Latin Americans" },
    excerpt: { es: "Desde 2 hasta 3 estrellas. Reservas, dress code, precios y que esperar en una cena Michelin.", en: "From 2 to 3 stars. Reservations, dress code, prices and what to expect at a Michelin dinner." },
    category: "gastronomia",
    categoryLabel: { es: "Gastronomia", en: "Gastronomy" },
    date: "12 Dic 2024",
    readTime: 9,
    featured: false,
    keywords: ["restaurantes michelin paris", "cena lujo paris", "gastronomia paris"],
  },
  {
    id: "esim-europa-guia",
    image: "https://images.unsplash.com/photo-1512941937669-90a1b58e7e9c?q=80&w=1200&auto=format&fit=crop",
    title: { es: "eSIM en Europa: Internet Ilimitado sin Roaming", en: "eSIM in Europe: Unlimited Internet without Roaming" },
    excerpt: { es: "Mejores opciones de eSIM, como activarla, precios y por que es mejor que el roaming tradicional.", en: "Best eSIM options, how to activate it, prices and why it's better than traditional roaming." },
    category: "consejos",
    categoryLabel: { es: "Consejos", en: "Tips" },
    date: "10 Dic 2024",
    readTime: 6,
    featured: false,
    keywords: ["esim europa", "internet europa", "roaming europa"],
  },
  {
    id: "amsterdam-tulipanes",
    image: "https://images.unsplash.com/photo-1534351590666-13e3e96b5017?q=80&w=1200&auto=format&fit=crop",
    title: { es: "Amsterdam y los Tulipanes: Mejor Epoca para Visitar", en: "Amsterdam and the Tulips: Best Time to Visit" },
    excerpt: { es: "Keukenhof, campos de tulipanes, canales y museos. Todo lo que necesitas para tu viaje.", en: "Keukenhof, tulip fields, canals and museums. Everything you need for your trip." },
    category: "destinos",
    categoryLabel: { es: "Destinos", en: "Destinations" },
    date: "8 Dic 2024",
    readTime: 7,
    featured: false,
    keywords: ["amsterdam tulipanes", "keukenhof", "holanda primavera"],
  },
  {
    id: "itinerario-espana-15-dias",
    image: "https://images.unsplash.com/photo-1558370781-d6196949e317?q=80&w=1200&auto=format&fit=crop",
    title: { es: "España en 15 Dias: Madrid, Barcelona, Sevilla y Mas", en: "Spain in 15 Days: Madrid, Barcelona, Seville and More" },
    excerpt: { es: "El itinerario perfecto para recorrer España. Rutas, transporte, alojamiento y consejos.", en: "The perfect itinerary to tour Spain. Routes, transport, accommodation and tips." },
    category: "destinos",
    categoryLabel: { es: "Destinos", en: "Destinations" },
    date: "6 Dic 2024",
    readTime: 14,
    featured: false,
    keywords: ["espana 15 dias", "itinerario espana", "que hacer en espana"],
  },
  {
    id: "trenes-europa-guia",
    image: "https://images.unsplash.com/photo-1474487548417-781cb71495f3?q=80&w=1200&auto=format&fit=crop",
    title: { es: "Guia de Trenes en Europa: Eurail, TGV, AVE y Mas", en: "Train Guide in Europe: Eurail, TGV, AVE and More" },
    excerpt: { es: "Como moverse en tren por Europa. Pases, reservas, precios y trucos para viajar comodo.", en: "How to get around Europe by train. Passes, reservations, prices and tips for comfortable travel." },
    category: "consejos",
    categoryLabel: { es: "Consejos", en: "Tips" },
    date: "4 Dic 2024",
    readTime: 11,
    featured: false,
    keywords: ["trenes europa", "eurail pass", "tren europa"],
  },
  {
    id: "londres-4-dias",
    image: "https://images.unsplash.com/photo-1513635269975-59663e0ac1ad?q=80&w=1200&auto=format&fit=crop",
    title: { es: "Londres en 4 Dias: Big Ben, Tower Bridge y Harry Potter", en: "London in 4 Days: Big Ben, Tower Bridge and Harry Potter" },
    excerpt: { es: "Itinerario completo incluyendo los estudios de Harry Potter. Imprescindibles y secretos locales.", en: "Complete itinerary including Harry Potter studios. Must-sees and local secrets." },
    category: "destinos",
    categoryLabel: { es: "Destinos", en: "Destinations" },
    date: "2 Dic 2024",
    readTime: 9,
    featured: false,
    keywords: ["londres 4 dias", "que hacer londres", "harry potter londres"],
  },
  {
    id: "tapas-madrid-guia",
    image: "https://images.unsplash.com/photo-1515443961218-a51367888e4b?q=80&w=1200&auto=format&fit=crop",
    title: { es: "Mejores Bares de Tapas en Madrid: Ruta Gastronomica", en: "Best Tapas Bars in Madrid: Gastronomic Route" },
    excerpt: { es: "La Latina, Malasana, Chueca. Los barrios con las mejores tapas y como hacer un 'tapeo'.", en: "La Latina, Malasana, Chueca. The neighborhoods with the best tapas and how to do a 'tapeo'." },
    category: "gastronomia",
    categoryLabel: { es: "Gastronomia", en: "Gastronomy" },
    date: "30 Nov 2024",
    readTime: 8,
    featured: false,
    keywords: ["tapas madrid", "donde comer madrid", "ruta tapas"],
  },
  {
    id: "venecia-sin-turistas",
    image: "https://images.unsplash.com/photo-1534113414509-0eec2bfb493f?q=80&w=1200&auto=format&fit=crop",
    title: { es: "Venecia sin Turistas: Trucos para Evitar Multitudes", en: "Venice Without Tourists: Tips to Avoid Crowds" },
    excerpt: { es: "Mejores horarios, barrios menos visitados, islas secretas y como disfrutar Venecia autentica.", en: "Best times, less visited neighborhoods, secret islands and how to enjoy authentic Venice." },
    category: "consejos",
    categoryLabel: { es: "Consejos", en: "Tips" },
    date: "28 Nov 2024",
    readTime: 7,
    featured: false,
    keywords: ["venecia sin turistas", "venecia secretos", "evitar multitudes venecia"],
  },
  {
    id: "praga-presupuesto",
    image: "https://images.unsplash.com/photo-1519677100203-a0e668c92439?q=80&w=1200&auto=format&fit=crop",
    title: { es: "Praga con Poco Presupuesto: Guia para Ahorrar", en: "Prague on a Budget: Money-Saving Guide" },
    excerpt: { es: "Praga es una de las capitales mas economicas de Europa. Alojamiento, comida y actividades baratas.", en: "Prague is one of Europe's most affordable capitals. Cheap accommodation, food and activities." },
    category: "dinero",
    categoryLabel: { es: "Dinero", en: "Money" },
    date: "26 Nov 2024",
    readTime: 8,
    featured: false,
    keywords: ["praga barato", "praga presupuesto", "europa economica"],
  },
  {
    id: "aurora-boreal-europa",
    image: "https://images.unsplash.com/photo-1531366936337-7c912a4589a7?q=80&w=1200&auto=format&fit=crop",
    title: { es: "Donde Ver la Aurora Boreal en Europa", en: "Where to See the Northern Lights in Europe" },
    excerpt: { es: "Noruega, Islandia, Finlandia y Suecia. Mejor epoca, lugares y consejos para ver auroras.", en: "Norway, Iceland, Finland and Sweden. Best time, places and tips for seeing auroras." },
    category: "destinos",
    categoryLabel: { es: "Destinos", en: "Destinations" },
    date: "24 Nov 2024",
    readTime: 9,
    featured: false,
    keywords: ["aurora boreal", "noruega aurora", "islandia luces norte"],
  },
  {
    id: "vinos-toscana",
    image: "https://images.unsplash.com/photo-1506377247377-2a5b3b417ebb?q=80&w=1200&auto=format&fit=crop",
    title: { es: "Ruta del Vino en la Toscana: Chianti y Brunello", en: "Wine Route in Tuscany: Chianti and Brunello" },
    excerpt: { es: "Bodegas, catas, paisajes y gastronomia. La guia definitiva para los amantes del vino italiano.", en: "Wineries, tastings, landscapes and gastronomy. The ultimate guide for Italian wine lovers." },
    category: "gastronomia",
    categoryLabel: { es: "Gastronomia", en: "Gastronomy" },
    date: "22 Nov 2024",
    readTime: 10,
    featured: false,
    keywords: ["vinos toscana", "chianti tour", "bodegas italia"],
  },
  {
    id: "grecia-islas-2-semanas",
    image: "https://images.unsplash.com/photo-1533105079780-92b9be482077?q=80&w=1200&auto=format&fit=crop",
    title: { es: "Islas Griegas en 2 Semanas: Santorini, Mykonos y Mas", en: "Greek Islands in 2 Weeks: Santorini, Mykonos and More" },
    excerpt: { es: "El island hopping perfecto. Que islas visitar, como moverse y donde alojarse.", en: "The perfect island hopping. Which islands to visit, how to get around and where to stay." },
    category: "destinos",
    categoryLabel: { es: "Destinos", en: "Destinations" },
    date: "20 Nov 2024",
    readTime: 12,
    featured: false,
    keywords: ["islas griegas", "santorini mykonos", "grecia vacaciones"],
  },
  {
    id: "berlin-muro-historia",
    image: "https://images.unsplash.com/photo-1560969184-10fe8719e047?q=80&w=1200&auto=format&fit=crop",
    title: { es: "Berlin: Historia del Muro y la Alemania Dividida", en: "Berlin: History of the Wall and Divided Germany" },
    excerpt: { es: "Checkpoint Charlie, East Side Gallery, Memorial del Muro. Un recorrido por la historia reciente.", en: "Checkpoint Charlie, East Side Gallery, Wall Memorial. A journey through recent history." },
    category: "destinos",
    categoryLabel: { es: "Destinos", en: "Destinations" },
    date: "18 Nov 2024",
    readTime: 9,
    featured: false,
    keywords: ["berlin muro", "historia alemania", "berlin turismo"],
  },
  {
    id: "costa-amalfitana-guia",
    image: "https://images.unsplash.com/photo-1534008897995-27a23e859048?q=80&w=1200&auto=format&fit=crop",
    title: { es: "Costa Amalfitana: Positano, Amalfi y Ravello", en: "Amalfi Coast: Positano, Amalfi and Ravello" },
    excerpt: { es: "Limoncello, casas coloridas y vistas al mar. Como recorrer la costa mas bella de Italia.", en: "Limoncello, colorful houses and sea views. How to tour the most beautiful coast in Italy." },
    category: "destinos",
    categoryLabel: { es: "Destinos", en: "Destinations" },
    date: "16 Nov 2024",
    readTime: 10,
    featured: false,
    keywords: ["costa amalfitana", "positano", "amalfi ravello"],
  },
  {
    id: "flamenco-sevilla",
    image: "https://images.unsplash.com/photo-1558370781-d6196949e317?q=80&w=1200&auto=format&fit=crop",
    title: { es: "Flamenco en Sevilla: Donde Ver Shows Autenticos", en: "Flamenco in Seville: Where to See Authentic Shows" },
    excerpt: { es: "Tablaos, peñas flamencas y festivales. Guia para vivir el flamenco como los locales.", en: "Tablaos, flamenco clubs and festivals. Guide to experience flamenco like the locals." },
    category: "lujo",
    categoryLabel: { es: "Lujo", en: "Luxury" },
    date: "14 Nov 2024",
    readTime: 7,
    featured: false,
    keywords: ["flamenco sevilla", "tablaos sevilla", "espectaculo flamenco"],
  },
  {
    id: "suiza-7-dias",
    image: "https://images.unsplash.com/photo-1530122037265-a5f1f91d3b99?q=80&w=1200&auto=format&fit=crop",
    title: { es: "Suiza en 7 Dias: Alpes, Lagos y Chocolate", en: "Switzerland in 7 Days: Alps, Lakes and Chocolate" },
    excerpt: { es: "Zurich, Lucerna, Interlaken, Zermatt. El itinerario perfecto por los Alpes suizos.", en: "Zurich, Lucerne, Interlaken, Zermatt. The perfect itinerary through the Swiss Alps." },
    category: "destinos",
    categoryLabel: { es: "Destinos", en: "Destinations" },
    date: "12 Nov 2024",
    readTime: 10,
    featured: false,
    keywords: ["suiza 7 dias", "itinerario suiza", "alpes suizos"],
  },
  {
    id: "primera-vez-europa",
    image: "https://images.unsplash.com/photo-1467269204594-9661b134dd2b?q=80&w=1200&auto=format&fit=crop",
    title: { es: "Primera Vez en Europa: 10 Errores que Debes Evitar", en: "First Time in Europe: 10 Mistakes to Avoid" },
    excerpt: { es: "No cometas estos errores clasicos de viajeros primerizos. Ahorra tiempo, dinero y frustraciones.", en: "Don't make these classic first-time traveler mistakes. Save time, money and frustrations." },
    category: "consejos",
    categoryLabel: { es: "Consejos", en: "Tips" },
    date: "10 Nov 2024",
    readTime: 8,
    featured: false,
    keywords: ["primera vez europa", "errores viaje europa", "consejos viajeros"],
  },
  {
    id: "croissants-paris",
    image: "https://images.unsplash.com/photo-1555507036-ab1f4038808a?q=80&w=1200&auto=format&fit=crop",
    title: { es: "Mejores Croissants de Paris: Top 10 Boulangeries", en: "Best Croissants in Paris: Top 10 Boulangeries" },
    excerpt: { es: "Donde encontrar los croissants mas deliciosos de Paris segun los parisinos.", en: "Where to find the most delicious croissants in Paris according to Parisians." },
    category: "gastronomia",
    categoryLabel: { es: "Gastronomia", en: "Gastronomy" },
    date: "8 Nov 2024",
    readTime: 6,
    featured: false,
    keywords: ["croissants paris", "boulangeries paris", "desayuno paris"],
  },
  {
    id: "portugal-10-dias",
    image: "https://images.unsplash.com/photo-1555881400-74d7acaacd8b?q=80&w=1200&auto=format&fit=crop",
    title: { es: "Portugal en 10 Dias: Lisboa, Porto, Algarve y Sintra", en: "Portugal in 10 Days: Lisbon, Porto, Algarve and Sintra" },
    excerpt: { es: "El pais mas accesible de Europa. Itinerario completo, precios y consejos.", en: "Europe's most accessible country. Complete itinerary, prices and tips." },
    category: "destinos",
    categoryLabel: { es: "Destinos", en: "Destinations" },
    date: "6 Nov 2024",
    readTime: 11,
    featured: false,
    keywords: ["portugal 10 dias", "itinerario portugal", "lisboa porto"],
  },
  {
    id: "compras-europa",
    image: "https://images.unsplash.com/photo-1483985988355-763728e1935b?q=80&w=1200&auto=format&fit=crop",
    title: { es: "Shopping en Europa: Tax Free, Outlets y Mejores Zonas", en: "Shopping in Europe: Tax Free, Outlets and Best Areas" },
    excerpt: { es: "Como aprovechar el Tax Free, los mejores outlets y zonas de compras por ciudad.", en: "How to take advantage of Tax Free, the best outlets and shopping areas by city." },
    category: "dinero",
    categoryLabel: { es: "Dinero", en: "Money" },
    date: "4 Nov 2024",
    readTime: 9,
    featured: false,
    keywords: ["compras europa", "tax free europa", "outlets europa"],
  },
  {
    id: "cinque-terre-guia",
    image: "https://images.unsplash.com/photo-1499678329028-101435549a4e?q=80&w=1200&auto=format&fit=crop",
    title: { es: "Cinque Terre: Las 5 Aldeas Coloridas de Italia", en: "Cinque Terre: Italy's 5 Colorful Villages" },
    excerpt: { es: "Riomaggiore, Manarola, Corniglia, Vernazza y Monterosso. Como visitarlas en un dia.", en: "Riomaggiore, Manarola, Corniglia, Vernazza and Monterosso. How to visit them in one day." },
    category: "destinos",
    categoryLabel: { es: "Destinos", en: "Destinations" },
    date: "2 Nov 2024",
    readTime: 8,
    featured: false,
    keywords: ["cinque terre", "cinco tierras italia", "aldeas coloridas"],
  },
  {
    id: "documentos-viajar-europa",
    image: "https://images.unsplash.com/photo-1551836022-d5d88e9218df?q=80&w=1200&auto=format&fit=crop",
    title: { es: "Documentos para Viajar a Europa: Checklist Completo 2026", en: "Documents for Traveling to Europe: Complete Checklist 2026" },
    excerpt: { es: "Pasaporte, visa, seguro, reservas de hotel. Todo lo que necesitas para pasar inmigracion sin problemas.", en: "Passport, visa, insurance, hotel reservations. Everything you need to pass immigration smoothly." },
    category: "consejos",
    categoryLabel: { es: "Consejos", en: "Tips" },
    date: "15 Ene 2026",
    readTime: 10,
    featured: true,
    keywords: ["documentos viajar europa", "requisitos viaje europa", "checklist europa", "visa schengen", "pasaporte europa"],
  },
  {
    id: "mejor-epoca-europa",
    image: "https://images.unsplash.com/photo-1489824904134-891ab64532f1?q=80&w=1200&auto=format&fit=crop",
    title: { es: "Mejor Epoca para Viajar a Europa por Destino", en: "Best Time to Travel to Europe by Destination" },
    excerpt: { es: "Cuando visitar cada pais segun el clima, precios y temporadas. Evita multitudes y ahorra dinero.", en: "When to visit each country based on weather, prices and seasons. Avoid crowds and save money." },
    category: "consejos",
    categoryLabel: { es: "Consejos", en: "Tips" },
    date: "28 Oct 2024",
    readTime: 9,
    featured: false,
    keywords: ["mejor epoca europa", "cuando viajar europa", "temporada europa"],
  },
  {
    id: "wifi-europa-datos",
    image: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?q=80&w=1200&auto=format&fit=crop",
    title: { es: "WiFi y Datos Moviles en Europa: eSIM vs Roaming", en: "WiFi and Mobile Data in Europe: eSIM vs Roaming" },
    excerpt: { es: "Las mejores opciones para tener internet en Europa. eSIM, chips locales y como evitar cargos sorpresa.", en: "The best options for internet in Europe. eSIM, local chips and how to avoid surprise charges." },
    category: "consejos",
    categoryLabel: { es: "Consejos", en: "Tips" },
    date: "26 Oct 2024",
    readTime: 6,
    featured: false,
    keywords: ["wifi europa", "datos moviles europa", "internet europa"],
  },
  {
    id: "moneda-europa-cambio",
    image: "https://images.unsplash.com/photo-1580519542036-c47de6196ba5?q=80&w=1200&auto=format&fit=crop",
    title: { es: "Cambio de Moneda en Europa: Euros, Tarjetas y ATMs", en: "Currency Exchange in Europe: Euros, Cards and ATMs" },
    excerpt: { es: "Donde cambiar dinero, que tarjetas usar y como evitar comisiones bancarias en Europa.", en: "Where to exchange money, which cards to use and how to avoid bank fees in Europe." },
    category: "dinero",
    categoryLabel: { es: "Dinero", en: "Money" },
    date: "24 Oct 2024",
    readTime: 7,
    featured: false,
    keywords: ["moneda europa", "cambio euro", "tarjetas europa ATM"],
  },
  {
    id: "hoteles-baratos-europa",
    image: "https://images.unsplash.com/photo-1566073771259-6a8506099945?q=80&w=1200&auto=format&fit=crop",
    title: { es: "Hoteles Baratos en Europa: Trucos para Ahorrar", en: "Cheap Hotels in Europe: Tricks to Save" },
    excerpt: { es: "Como encontrar alojamiento economico sin sacrificar calidad. Booking hacks y alternativas.", en: "How to find budget accommodation without sacrificing quality. Booking hacks and alternatives." },
    category: "dinero",
    categoryLabel: { es: "Dinero", en: "Money" },
    date: "22 Oct 2024",
    readTime: 8,
    featured: false,
    keywords: ["hoteles baratos europa", "alojamiento economico", "donde hospedarse"],
  },
  {
    id: "pasaporte-europa-requisitos",
    image: "https://images.unsplash.com/photo-1544636331-e26879cd4d9b?q=80&w=1200&auto=format&fit=crop",
    title: { es: "Requisitos del Pasaporte para Viajar a Europa 2026", en: "Passport Requirements for Traveling to Europe 2026" },
    excerpt: { es: "Vigencia minima, paginas en blanco, renovacion y casos especiales para pasaportes latinoamericanos.", en: "Minimum validity, blank pages, renewal and special cases for Latin American passports." },
    category: "planificacion",
    categoryLabel: { es: "Planificacion", en: "Planning" },
    date: "20 Oct 2025",
    readTime: 6,
    featured: false,
    keywords: ["pasaporte europa", "requisitos pasaporte", "vigencia pasaporte"],
  },
  {
    id: "eurail-pass-guia",
    image: "https://images.unsplash.com/photo-1474487548417-781cb71495f3?q=80&w=1200&auto=format&fit=crop",
    title: { es: "Eurail Pass: Vale la Pena? Guia Completa 2025", en: "Eurail Pass: Is It Worth It? Complete Guide 2025" },
    excerpt: { es: "Tipos de pases, precios, como reservar asientos y en que casos conviene comprarlo.", en: "Types of passes, prices, how to reserve seats and when it's worth buying." },
    category: "dinero",
    categoryLabel: { es: "Dinero", en: "Money" },
    date: "18 Oct 2024",
    readTime: 10,
    featured: false,
    keywords: ["eurail pass", "tren europa", "pase tren europeo"],
  },
  {
    id: "barcelona-gaudi",
    image: "https://images.unsplash.com/photo-1583422409516-2895a77efded?q=80&w=1200&auto=format&fit=crop",
    title: { es: "Ruta Gaudi en Barcelona: Sagrada Familia, Park Guell y Mas", en: "Gaudi Route in Barcelona: Sagrada Familia, Park Guell and More" },
    excerpt: { es: "Todas las obras del arquitecto mas famoso de España. Entradas, horarios y consejos de visita.", en: "All the works of Spain's most famous architect. Tickets, schedules and visiting tips." },
    category: "destinos",
    categoryLabel: { es: "Destinos", en: "Destinations" },
    date: "16 Oct 2024",
    readTime: 9,
    featured: false,
    keywords: ["gaudi barcelona", "sagrada familia", "park guell"],
  },
  {
    id: "museo-louvre-guia",
    image: "https://images.unsplash.com/photo-1499426600726-ac36d2d0c569?q=80&w=1200&auto=format&fit=crop",
    title: { es: "Museo del Louvre: Guia para No Perderte Nada", en: "Louvre Museum: Guide to Not Miss Anything" },
    excerpt: { es: "Mona Lisa, Venus de Milo y 35,000 obras. Como recorrerlo en 3 horas sin agotarte.", en: "Mona Lisa, Venus de Milo and 35,000 works. How to tour it in 3 hours without exhaustion." },
    category: "destinos",
    categoryLabel: { es: "Destinos", en: "Destinations" },
    date: "14 Oct 2024",
    readTime: 8,
    featured: false,
    keywords: ["louvre paris", "museo louvre", "que ver louvre"],
  },
  {
    id: "malta-verano",
    image: "/assets/Gemini_Generated_Image_jw4y04jw4y04jw4y_1767447444765.png",
    title: { es: "Malta en Verano: Playas Secretas y Cultura Milenaria", en: "Malta in Summer: Secret Beaches and Ancient Culture" },
    excerpt: { es: "Valletta, Blue Lagoon, Gozo. El destino secreto del Mediterraneo con historia fascinante.", en: "Valletta, Blue Lagoon, Gozo. The secret Mediterranean destination with fascinating history." },
    category: "destinos",
    categoryLabel: { es: "Destinos", en: "Destinations" },
    date: "02 Ene 2026",
    readTime: 8,
    featured: false,
    keywords: ["malta verano", "blue lagoon malta", "valletta"],
  },
  {
    id: "viena-musica-clasica",
    image: "https://images.unsplash.com/photo-1519677100203-a0e668c92439?q=80&w=1200&auto=format&fit=crop",
    title: { es: "Viena Musical: Opera, Mozart y Conciertos", en: "Musical Vienna: Opera, Mozart and Concerts" },
    excerpt: { es: "Opera de Viena, conciertos en palacios, casa de Mozart. Guia para amantes de la musica clasica.", en: "Vienna Opera, palace concerts, Mozart's house. Guide for classical music lovers." },
    category: "lujo",
    categoryLabel: { es: "Lujo", en: "Luxury" },
    date: "10 Oct 2024",
    readTime: 9,
    featured: false,
    keywords: ["viena opera", "conciertos viena", "musica clasica europa"],
  },
  {
    id: "dublin-pubs-guinness",
    image: "https://images.unsplash.com/photo-1549918864-48ac978761a4?q=80&w=1200&auto=format&fit=crop",
    title: { es: "Dublin: Pubs, Guinness y Encanto Irlandes", en: "Dublin: Pubs, Guinness and Irish Charm" },
    excerpt: { es: "Temple Bar, Guinness Storehouse, Trinity College. La capital irlandesa en 3 dias.", en: "Temple Bar, Guinness Storehouse, Trinity College. The Irish capital in 3 days." },
    category: "destinos",
    categoryLabel: { es: "Destinos", en: "Destinations" },
    date: "8 Oct 2024",
    readTime: 7,
    featured: false,
    keywords: ["dublin pubs", "guinness storehouse", "irlanda turismo"],
  },
  {
    id: "brujas-belgica",
    image: "https://images.unsplash.com/photo-1491557345352-5929e343eb89?q=80&w=1200&auto=format&fit=crop",
    title: { es: "Brujas: La Ciudad Medieval de Chocolate y Canales", en: "Bruges: The Medieval City of Chocolate and Canals" },
    excerpt: { es: "Canales, chocolate, cervezas trapenses y arquitectura medieval. Brujas en un dia.", en: "Canals, chocolate, Trappist beers and medieval architecture. Bruges in one day." },
    category: "destinos",
    categoryLabel: { es: "Destinos", en: "Destinations" },
    date: "6 Oct 2024",
    readTime: 6,
    featured: false,
    keywords: ["brujas belgica", "chocolate belga", "canales brujas"],
  },
  {
    id: "noruega-fiordos",
    image: "https://images.unsplash.com/photo-1531366936337-7c912a4589a7?q=80&w=1200&auto=format&fit=crop",
    title: { es: "Fiordos de Noruega: Geiranger, Trolltunga y Mas", en: "Norwegian Fjords: Geiranger, Trolltunga and More" },
    excerpt: { es: "Los paisajes mas espectaculares de Europa. Como recorrer los fiordos noruegos en 7 dias.", en: "Europe's most spectacular landscapes. How to tour the Norwegian fjords in 7 days." },
    category: "destinos",
    categoryLabel: { es: "Destinos", en: "Destinations" },
    date: "4 Oct 2024",
    readTime: 11,
    featured: false,
    keywords: ["fiordos noruega", "geiranger", "trolltunga"],
  },
  {
    id: "budapest-baños-termales",
    image: "https://images.unsplash.com/photo-1551867633-194f125bddfa?q=80&w=1200&auto=format&fit=crop",
    title: { es: "Budapest: Banos Termales, Ruin Bars y el Danubio", en: "Budapest: Thermal Baths, Ruin Bars and the Danube" },
    excerpt: { es: "Szechenyi, Gellert, Parlamento y la vida nocturna en bares de ruinas. Budapest completo.", en: "Szechenyi, Gellert, Parliament and nightlife in ruin bars. Complete Budapest." },
    category: "destinos",
    categoryLabel: { es: "Destinos", en: "Destinations" },
    date: "2 Oct 2024",
    readTime: 10,
    featured: false,
    keywords: ["budapest baños termales", "ruin bars", "hungria turismo"],
  },
  {
    id: "escocia-highlands",
    image: "https://images.unsplash.com/photo-1506905925346-21bda4d32df4?q=80&w=1200&auto=format&fit=crop",
    title: { es: "Escocia: Highlands, Castillos y Whisky", en: "Scotland: Highlands, Castles and Whisky" },
    excerpt: { es: "Edimburgo, Lago Ness, Isla de Skye. Ruta por las tierras altas escocesas.", en: "Edinburgh, Loch Ness, Isle of Skye. Route through the Scottish highlands." },
    category: "destinos",
    categoryLabel: { es: "Destinos", en: "Destinations" },
    date: "30 Sep 2024",
    readTime: 12,
    featured: false,
    keywords: ["escocia highlands", "lago ness", "whisky escocia"],
  },
];
